//! @generated endpoint catalog — do not edit by hand.
//! Source: observed from the Lofty marketplace SPA endpoint registry.

use Kind::*;

/// Safety classification of an endpoint.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Kind {
    /// Safe read; no mutation, no spend.
    Read,
    /// Mutates account state, places orders, or moves money.
    Write,
    /// Administrative; not usable by normal accounts.
    Admin,
}

/// One platform endpoint.
#[derive(Clone, Copy, Debug, serde::Serialize)]
pub struct Endpoint {
    pub path: &'static str,
    pub name: &'static str,
    pub group: &'static str,
    pub kind: Kind,
}

/// The full observed platform surface (124 endpoints).
pub const ENDPOINTS: &[Endpoint] = &[
    Endpoint {
        path: "/admin/v2/config",
        name: "adminConfig",
        group: "admin",
        kind: Admin,
    },
    Endpoint {
        path: "/admin/v2/oracle-price-infos",
        name: "adminGetOraclePriceInfos",
        group: "admin",
        kind: Admin,
    },
    Endpoint {
        path: "/admin/v2/oracle-prices/cache",
        name: "adminCacheOraclePrices",
        group: "admin",
        kind: Admin,
    },
    Endpoint {
        path: "/admin/v2/oracle-prices/update",
        name: "adminUpdateOraclePrices",
        group: "admin",
        kind: Admin,
    },
    Endpoint {
        path: "/algocontracts/v1/claim-redeem",
        name: "claimRedeem",
        group: "algocontracts",
        kind: Write,
    },
    Endpoint {
        path: "/algocontracts/v1/claim-swap",
        name: "claimSwap",
        group: "algocontracts",
        kind: Write,
    },
    Endpoint {
        path: "/blog/v2/categories",
        name: "blogCategories",
        group: "blog",
        kind: Read,
    },
    Endpoint {
        path: "/blog/v2/entry",
        name: "blogEntry",
        group: "blog",
        kind: Read,
    },
    Endpoint {
        path: "/blog/v2/home",
        name: "blogHome",
        group: "blog",
        kind: Read,
    },
    Endpoint {
        path: "/emails/v2/save",
        name: "saveEmail",
        group: "emails",
        kind: Write,
    },
    Endpoint {
        path: "/exchange/v2/cancelorder",
        name: "cancelorder",
        group: "exchange",
        kind: Write,
    },
    Endpoint {
        path: "/exchange/v2/create-pending-order",
        name: "createPendingOrder",
        group: "exchange",
        kind: Write,
    },
    Endpoint {
        path: "/exchange/v2/createorder",
        name: "createorder",
        group: "exchange",
        kind: Write,
    },
    Endpoint {
        path: "/exchange/v2/get-order-state",
        name: "getOrderState",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/getorderandstreams",
        name: "getOrderAndStreams",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/getpropertyinfo",
        name: "getpropertyinfo",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/getpropertyorderbook",
        name: "getpropertyorderbook",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/getpropertytxns",
        name: "getpropertytxns",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/getuserinfo",
        name: "getuserinfo",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/getwatchedescrows",
        name: "getwatchedescrows",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/getwatchedswaps",
        name: "getwatchedswaps",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/signcontract",
        name: "signcontract",
        group: "exchange",
        kind: Write,
    },
    Endpoint {
        path: "/exchange/v2/validateOrder",
        name: "validateOrder",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/exchange/v2/watchtransaction",
        name: "watchtransaction",
        group: "exchange",
        kind: Read,
    },
    Endpoint {
        path: "/geolocation/v2/geocode",
        name: "geocode",
        group: "geolocation",
        kind: Read,
    },
    Endpoint {
        path: "/liquidity/v1/batch",
        name: "reportBatchTransaction",
        group: "liquidity",
        kind: Write,
    },
    Endpoint {
        path: "/lp-rewards/dashboard",
        name: "getLpRewardsDashboard",
        group: "lp-rewards",
        kind: Read,
    },
    Endpoint {
        path: "/lp-rewards/enabled",
        name: "getEnabledLpRewardsProperties",
        group: "lp-rewards",
        kind: Read,
    },
    Endpoint {
        path: "/lp-rewards/history",
        name: "getLpRewardHistory",
        group: "lp-rewards",
        kind: Read,
    },
    Endpoint {
        path: "/marketing/v2/analytics/signup-attribution",
        name: "getSignupAttributionReport",
        group: "marketing",
        kind: Write,
    },
    Endpoint {
        path: "/marketing/v2/property-lead",
        name: "createPropertyLead",
        group: "marketing",
        kind: Write,
    },
    Endpoint {
        path: "/marketing/v2/referrals/leaderboard",
        name: "getReferralLeaderboard",
        group: "marketing",
        kind: Read,
    },
    Endpoint {
        path: "/marketing/v2/referrals/status",
        name: "getReferralStatus",
        group: "marketing",
        kind: Read,
    },
    Endpoint {
        path: "/payments/v2/add-payment-method",
        name: "addPaymentMethod",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/bank-payment-intent",
        name: "createBankPaymentIntent",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/begin-deposit",
        name: "beginDepositPayment",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/begin-transaction",
        name: "beginPaymentTransaction",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/cancel-transaction",
        name: "cancelTransaction",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/confirm-opt-in",
        name: "confirmOptIn",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/create-checkout-session",
        name: "createCheckoutSession",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/create-setup-intent",
        name: "manageStripeSetupIntent",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/delete-payment-method",
        name: "deletePaymentMethod",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/deposits",
        name: "getDeposits",
        group: "payments",
        kind: Read,
    },
    Endpoint {
        path: "/payments/v2/exchange-rates",
        name: "getCryptoQuotes",
        group: "payments",
        kind: Read,
    },
    Endpoint {
        path: "/payments/v2/list-payment-methods",
        name: "listPaymentMethods",
        group: "payments",
        kind: Read,
    },
    Endpoint {
        path: "/payments/v2/payment-intent",
        name: "manageStripePaymentIntent",
        group: "payments",
        kind: Read,
    },
    Endpoint {
        path: "/payments/v2/payment-params",
        name: "getUserPaymentParams",
        group: "payments",
        kind: Read,
    },
    Endpoint {
        path: "/payments/v2/payment-settings",
        name: "setPaymentDefaults",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/payments/v2/transaction-status",
        name: "getTransactionStatus",
        group: "payments",
        kind: Read,
    },
    Endpoint {
        path: "/payments/v2/update-payment-transaction",
        name: "updateCryptoTransaction",
        group: "payments",
        kind: Write,
    },
    Endpoint {
        path: "/properties/v2/featured",
        name: "getFeaturedProperties",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/get-list-view-data",
        name: "getListViewData",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/get-list-view-data-by-id",
        name: "getListViewDataById",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/get-list-view-data-by-ids",
        name: "getListViewDataByIds",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/get-property-reviews",
        name: "getPropertyReviewsData",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/get-property-yields",
        name: "getPropertyYields",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/lookup",
        name: "lookupProperty",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/marketplace",
        name: "getMarketplaceProperties",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/oracle-price",
        name: "getPropertyOraclePrice",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/property",
        name: "getPropertyById",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/properties/v2/ticker",
        name: "getPropertiesTicker",
        group: "properties",
        kind: Read,
    },
    Endpoint {
        path: "/property-managers/v2/create-pl-entry",
        name: "managerCreatePLEntry",
        group: "property-managers",
        kind: Write,
    },
    Endpoint {
        path: "/property-managers/v2/get-manager-properties",
        name: "getManagerProperties",
        group: "property-managers",
        kind: Read,
    },
    Endpoint {
        path: "/property-managers/v2/get-pl-entry",
        name: "managerGetPLEntry",
        group: "property-managers",
        kind: Read,
    },
    Endpoint {
        path: "/property-managers/v2/pl-cutoff-config",
        name: "getPlCutoffConfig",
        group: "property-managers",
        kind: Read,
    },
    Endpoint {
        path: "/property-managers/v2/send-property-updates",
        name: "managerSendPropertyUpdates",
        group: "property-managers",
        kind: Write,
    },
    Endpoint {
        path: "/property-managers/v2/update-manager-property",
        name: "updateManagerProperty",
        group: "property-managers",
        kind: Write,
    },
    Endpoint {
        path: "/property-managers/v2/update-pl-entry",
        name: "managerUpdatePLEntry",
        group: "property-managers",
        kind: Write,
    },
    Endpoint {
        path: "/taxdocuments/v2/all",
        name: "getAllDocuments",
        group: "taxdocuments",
        kind: Read,
    },
    Endpoint {
        path: "/taxdocuments/v2/zip-documents",
        name: "getZipFile",
        group: "taxdocuments",
        kind: Read,
    },
    Endpoint {
        path: "/transactions/v2/createReinvestment",
        name: "createReinvestment",
        group: "transactions",
        kind: Write,
    },
    Endpoint {
        path: "/transactions/v2/createwithdrawal",
        name: "createWithdrawalTransaction",
        group: "transactions",
        kind: Write,
    },
    Endpoint {
        path: "/transactions/v2/getTransactionById",
        name: "getTransactionById",
        group: "transactions",
        kind: Read,
    },
    Endpoint {
        path: "/transactions/v2/getbyuser",
        name: "getUserTransactions",
        group: "transactions",
        kind: Read,
    },
    Endpoint {
        path: "/transactions/v2/getcryptopurchase",
        name: "getCryptoPurchase",
        group: "transactions",
        kind: Read,
    },
    Endpoint {
        path: "/transactions/v2/getusersummary",
        name: "getUserSummaryTransactions",
        group: "transactions",
        kind: Read,
    },
    Endpoint {
        path: "/transactions/v2/referral-totals",
        name: "getReferralTotals",
        group: "transactions",
        kind: Read,
    },
    Endpoint {
        path: "/transactions/v2/stats-summary",
        name: "getSummaryStatisticsOnOurSuccess",
        group: "transactions",
        kind: Read,
    },
    Endpoint {
        path: "/transactions/v2/withdrawals",
        name: "getUserWithdrawals",
        group: "transactions",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/add-prop-watchlist",
        name: "addPropToUsersWatchlist",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/api-keys",
        name: "apiKeys",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/backup-codes",
        name: "getBackupCodes",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/bank-account",
        name: "addbankaccount",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/bank-account/remove",
        name: "removebankaccount",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/code/request",
        name: "requestCode",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/code/verify",
        name: "verifyCode",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/confirm-code",
        name: "confirmBackupCode",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/countries",
        name: "getCountries",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/create-review",
        name: "createUserReview",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/delete-review",
        name: "deleteUserReview",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/finalize-email-change",
        name: "finalizeEmailChange",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/finalize-sms2fa-phone",
        name: "finalizeSms2faPhoneVerification",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/get",
        name: "getuser",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/get-user-cocs",
        name: "getUserCocs",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/get-user-reviews",
        name: "getUserReviews",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/get-users-watchlist",
        name: "getUsersWatchlist",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/getbdata",
        name: "getuserbdata",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/gift-escrow-lockup-summary",
        name: "getGiftEscrowLockupSummary",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/gift-escrow-lockups",
        name: "getGiftEscrowLockups",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/mfa-settings",
        name: "updateMfaSettings",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/portfolio-snapshots",
        name: "getPortfolioSnapshots",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/prepare-sms2fa-phone",
        name: "prepareSms2faPhoneVerification",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/sign-dao-agreement",
        name: "signDaoAgreement",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/status-summary",
        name: "getStatusSummary",
        group: "users",
        kind: Read,
    },
    Endpoint {
        path: "/users/v2/update",
        name: "updateuser",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/update-prop-watchlist",
        name: "updatePropOnUsersWatchlist",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/update-review",
        name: "updateUserReview",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/users/v2/verify-email",
        name: "verifyEmail",
        group: "users",
        kind: Write,
    },
    Endpoint {
        path: "/verifications/v2/completeIdValidation",
        name: "completeIdValidation",
        group: "verifications",
        kind: Write,
    },
    Endpoint {
        path: "/verifications/v2/finalizePhoneVerification",
        name: "finalizePhoneVerification",
        group: "verifications",
        kind: Write,
    },
    Endpoint {
        path: "/verifications/v2/getTokens",
        name: "getVerificationTokens",
        group: "verifications",
        kind: Read,
    },
    Endpoint {
        path: "/verifications/v2/retry",
        name: "retrytVerification",
        group: "verifications",
        kind: Write,
    },
    Endpoint {
        path: "/verifications/v2/verifiedCall",
        name: "verifiedCall",
        group: "verifications",
        kind: Read,
    },
    Endpoint {
        path: "/verifications/v2/verifyPhoneCodeCheck",
        name: "verifyPhoneCodeCheck",
        group: "verifications",
        kind: Write,
    },
    Endpoint {
        path: "/verifications/v2/verifyPhoneNumber",
        name: "verifyPhoneNumber",
        group: "verifications",
        kind: Write,
    },
    Endpoint {
        path: "/wallet/v2/add-external-wallet",
        name: "addExternalWallet",
        group: "wallet",
        kind: Write,
    },
    Endpoint {
        path: "/wallet/v2/address",
        name: "getWallet",
        group: "wallet",
        kind: Read,
    },
    Endpoint {
        path: "/wallet/v2/claimNft",
        name: "claimNft",
        group: "wallet",
        kind: Write,
    },
    Endpoint {
        path: "/wallet/v2/create-send-transaction",
        name: "createSendTransaction",
        group: "wallet",
        kind: Write,
    },
    Endpoint {
        path: "/wallet/v2/delete-mnemonic",
        name: "deleteWalletMnemonic",
        group: "wallet",
        kind: Write,
    },
    Endpoint {
        path: "/wallet/v2/get-all",
        name: "getAllWallets",
        group: "wallet",
        kind: Read,
    },
    Endpoint {
        path: "/wallet/v2/get-mnemonic",
        name: "getWalletMnemonic",
        group: "wallet",
        kind: Read,
    },
    Endpoint {
        path: "/wallet/v2/remove-external-wallet",
        name: "removeExternalWallet",
        group: "wallet",
        kind: Write,
    },
    Endpoint {
        path: "/wallet/v2/send-nft-to-external-wallet",
        name: "sendNftToExternalWallet",
        group: "wallet",
        kind: Write,
    },
];
